CREATE TABLE adm_assinatura (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	nome TEXT,
	email TEXT,
	cpf TEXT,
	id_adm_plano INTEGER,
	dt_criacao DATETIME,
	dt_excluido DATETIME,
	status TEXT,
	dt_nascimento DATE,
	dt_demonstracao DATETIME,
	dt_bloqueio DATETIME,
	cep TEXT,
	telefone TEXT,
	endereco TEXT,
	numero TEXT,
	complemento TEXT,
	bairro TEXT,
	cidade TEXT,
	uf TEXT,
	stripe_customer_id TEXT,
	stripe_subscription_id TEXT,
	stripe_payment_method_id TEXT
);